JOS_PRODUCT_VERSION_NUMBER = 15
JOS_PRODUCT_VERSION_CODENAME = Obsidian

# jOS version
JOS_VERSION := $(JOS_PRODUCT_VERSION_NUMBER)-$(BUILD_NUMBER_FROM_FILE)-($(JOS_PRODUCT_VERSION_CODENAME))

PRODUCT_PRODUCT_PROPERTIES += \
    ro.j.osversion=$(JOS_VERSION) \
