JOS_PRODUCT_VERSION_MAJOR = 15
JOS_PRODUCT_VERSION_MINOR = 1 # WILL BE REMOVED WITH JOS 16
JOS_PRODUCT_VERSION_CODENAME = Obsidian

# jOS version
JOS_VERSION := $(JOS_PRODUCT_VERSION_MAJOR).$(JOS_PRODUCT_VERSION_MINOR)-($(JOS_PRODUCT_VERSION_CODENAME))

# jOS Internal version (Shorter version string mainly used for comparing jOS Versions)
JOS_INTERNAL_VERSION := $(JOS_PRODUCT_VERSION_MAJOR)$(BUILD_NUMBER_FROM_FILE)

PRODUCT_PRODUCT_PROPERTIES += \
    ro.j.osversion=$(JOS_VERSION) \
    ro.j.osinternalversion=$(JOS_INTERNAL_VERSION) \
    ro.j.oscodename=$(JOS_PRODUCT_VERSION_CODENAME) \
